### ISSUE TITLE
Problème à l'installation

### ISSUE THREAD

**Issue by NobleCathare** [OPEN-DSI/ecommerceng_woosync#27]
Sur Dolibarr 12.0.1

Les fichiers décompressés dans /custom

Fatal error: Class 'eCommerceSite' not found in /homepages/30/d692085464/htdocs/crm/htdocs/custom/woosync/core/modules/modECommerceNg.class.php on line 144

**Comment by philippe-opendsi** [comment]
Bonjour 
Il faut renommer le dossier décompressé en ecommerceng
Attention à partir de la version 4.0.47 le module a été repris en profondeur dans ces mécanismes de fonctionnement. La documentation n'est plus à jour. Sa mise à jour est en cours.
Nous vous conseillons soit d'attendre la mise à jour de celle-ci soit d'installer la 4.0.46 en attendant.
Cordialement

**Comment by Pillow69** [comment]
Merci, cela répond exactement à mon bug d'installation.
