### ISSUE TITLE
Compatibilité avec Dolibarr 13.0.3 ? / Compatibility with Dolibarr 13.0.3 ? 

### ISSUE THREAD

**Issue by Bessonweb** [OPEN-DSI/ecommerceng_woosync#35]
Bonjour,

Quelqu'un pourrait-il me confirmer ou m'infirmer la compatibilité de ce module avec la version 13.0.3 de Dolibarr s'il vous plait ?

Merci !

----------------------------------

Hello,

Could someone confirm or deny me the compatibility of this module with Dolibarr version 13.0.3 please?

Thank you!

**Comment by philippe-opendsi** [comment]
Bonjour
Pour l'instant pas de Dolibarr en production sur cette version à notre connaissance. A tester avant mise en production.

**Comment by Bessonweb** [comment]
Merci de la réponse !

Je sais pas si j'aurais le temps de tester, mais sinon je vous tiendrais au courant

**Comment by philippe-opendsi** [comment]
Mise à disposition d'une version avec qque fix pour la v13.

**Comment by Bessonweb** [comment]
Bonjour et merci pour la mise à jour je veillerais à l'appliquer !

Pour l'instant en tous cas mes tests sont concluants et le module semble fonctionner à merveille !

Si je peux me permettre, j'aurais juste quelque petites observations : 

- La doc (PDF) n'est pas toujours d'actualité niveau instructions, notamment sur WooCommerce et OauthServer.
- Certains paramètres ne peuvent être configurés qu'une fois que l'instance du site Wordpress est créé sur Dolibarr, peut-être faudrait-il mettre à jour la Doc. à ce propos ?
- Certains messages d'erreur ne sont pas très explicites ou alors n'ont pas le bon déclencheur.
  - par exemple, mes produits n'avaient pas de référence (UGS sur WooCommerce), mais le message d'erreur qui s'affichait n'était pas très clair.

Sinon tout s'est plutôt bien passé, faut bien lire. La compatibilité avec la V13 semble bonne, en tous cas je n'ai pas rencontré de dysfonctionnement.

Merci à vous !

**Comment by philippe-opendsi** [comment]
Bonjour
N'hésitez pas à contribuer des améliorations sur la documentation. Nous les intégrerons avec plaisir :-)

**Comment by Bessonweb** [comment]
Je vais essayer de faire ça quand je passerais en prod en faisant des captures et en essayant d'expliquer le parcours.
